#!/bin/bash

case $BLOCK_NAME in
	upload)
		TYPE=tx
		COLOR='#FF3333'
		;;
	download)
		TYPE=rx
		COLOR='#00FF00'
		;;
	*)
		echo  666 TB/s
		echo  666 TB/s
		echo '#F10399'
		exit 1
		;;
esac

FILE=$XDG_RUNTIME_DIR/i3blocks_bandwidth_$TYPE
touch $FILE

PREV=$(cat $FILE)
CUR=0
for IFACE in wlan0 enp2s0f0 enp6s0; do
    if ip link show $IFACE | grep -q 'state UP'; then
        F=/sys/class/net/$IFACE/statistics/${TYPE}_bytes
        N=$(cat $F)
        CUR=$(expr $CUR + $N)
    fi
done

delta=$(expr $CUR - $PREV)
RATE=$(expr $delta / 1000)

echo $RATE kB/s
echo $RATE kB/s
echo $COLOR

echo $CUR > $FILE
exit 0;
