#!/bin/bash

FULLBAT=""
HALFBAT=""
QUARTBAT=""
THREEQUARTBAT=""
EMPBAT=""
discharging_status="Δ"
charging_status=""


STATUS=$( acpi | awk '{print $3}' )
THRESHOLD=5

if [ "$STATUS" = "Discharging," ]
then
        STATUS=$discharging_status
else
        STATUS=$charging_status
fi

PERCENT=$( acpi | awk '{print $4}' )
VAL=${PERCENT//[^0-9]/}

R=$(expr \( 255 \* \( 100 - $VAL \) \) / 100 )
G=$(expr \( 255 \* $VAL \) / 100 )
B=20

if [ "$VAL" -gt 75 ]; then
    ICON=$FULLBAT
elif [ "$VAL" -gt 50 ]; then
    ICON=$THREEQUARTBAT
elif [ "$VAL" -gt 25 ]; then
    ICON=$HALFBAT
else
    ICON=$EMPBAT
fi

COLOR=$($XDG_CONFIG_HOME/i3blocks/scripts/battery.py $VAL)
case $BLOCK_BUTTON in
  1)
    echo $(printf '%s %d%%' $STATUS $VAL)
	echo
    echo $COLOR
	exit;
	#exit 33;
	;;
esac


echo $(printf '%s %s' $STATUS $ICON)
echo $(printf '%s %d%%' $STATUS $VAL)
echo $COLOR

if [ $VAL -le 15 ] && [ $STATUS == $discharging_status ]; then
	summary='Low Battery'
    icon="battery-low"

	if [ $VAL -le 5 ]; then
	   summary='Battery Critical'
	   icon="battery-caution"
	fi

	/usr/bin/notify-send \
		"$summary" \
		"$VAL% remaining" \
		-u CRITICAL \
		-i "$icon"
fi

[ $VAL -le $THRESHOLD ] && exit 33 || exit 0;
