#!/bin/sh

ticker="$(curl 'https://api.coinmarketcap.com/v1/ticker/'"$BLOCK_INSTANCE"'/' -s | jq '.[0]["price_usd"]' | sed 's/"//g') USD"

echo $ticker
echo $ticker

case $BLOCK_INSTANCE in
bitcoin)
    echo \#F89F33
    ;;
*)
    echo \#FFFFFF
    ;;
esac
