#!/bin/bash

#weather=$(cd ~/scripts/weatherpy && $XDG_CONFIG_HOME/i3blocks/scripts/weather.py $BLOCK_INSTANCE)
weather=$(cd ~/scripts/weatherpy && pipenv run python weather.py $BLOCK_INSTANCE)

echo $weather
echo $weather
echo \#85A9FF
