directory: ~/Music
library: ~/etc/beets/library.db
plugins: duplicates


#Either yes or no, indicating whether the autotagger should use multiple threads.
#This makes things faster but may behave strangely.  Defaults to yes.
threaded: yes
ui:
    color: yes
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: red
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue
