#!/bin/sh

TARGET=/run/media/victor/backup/wonton

if [ -d $TARGET ]; then
    echo "backing up system to $TARGET"
    START=$(date +%s)
    sudo rsync -axAX --progress --delete --ignore-errors / "$TARGET/rootfs/" > ~/rootfs.backup
    sudo rsync -axAX --progress --delete --ignore-errors /boot/ "$TARGET/boot/" > ~/boot.backup
    sudo rsync -axAX --progress --delete --ignore-errors /home/ "$TARGET/home/" > ~/home.backup
    FINISH=$(date +%s)

    echo "total time: $(( ($FINISH-$START) / 60 )) minutes, $(( ($FINISH-$START) % 60 )) seconds"
    #touch $TARGET/"Backup from $(date '+%A, %d %B %Y, %T')"
else
    echo "$TARGET not found"
fi
