# external/thirdparty formulas
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "rs/tap"
tap "universal-ctags/universal-ctags"
# 
brew "adr-tools"
brew "openssl"
brew "aria2"
brew "gettext"
brew "libffi"
brew "atk"
brew "automake"
brew "readline"
brew "sqlite"
brew "python"
brew "awscli"
brew "awslogs"
brew "cython"
brew "cassandra"
brew "cfssl"
brew "coreutils"
brew "go"
brew "dep"
brew "direnv"
brew "fail2ban"
brew "icu4c"
brew "ffmpeg"
brew "fish"
brew "flyway"
brew "gdk-pixbuf"
brew "git"
brew "git-crypt"
brew "git-standup"
brew "glib-openssl"
brew "glide"
brew "gnu-sed"
brew "gobject-introspection"
brew "gperftools"
brew "hicolor-icon-theme"
brew "pango"
brew "httpie"
brew "iperf"
brew "iproute2mac"
brew "jmeter"
brew "node"
brew "jsonlint"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "kustomize"
brew "libdbi"
brew "libgpg-error"
brew "libxmlsec1"
brew "llvm"
brew "lua@5.1"
brew "mas"
brew "memcached"
brew "mysql", link: false
brew "mysql-client", link: true
brew "neovim"
brew "newsboat"
brew "nmap"
brew "node@8"
brew "nvm"
brew "nyancat"
brew "oath-toolkit"
brew "openssl@1.1"
brew "packer"
brew "parallel"
brew "perl", link: false
brew "pidgin"
brew "postgresql"
brew "python@2"
brew "qrencode"
brew "reattach-to-user-namespace"
brew "redis"
brew "rename"
brew "shared-mime-info"
brew "shpotify"
brew "siege"
brew "sphinx-doc"
brew "stow"
brew "switchaudio-osx"
brew "sysbench"
brew "task"
brew "tasksh"
brew "thefuck"
brew "tmux"
brew "urlview"
brew "vegeta"
brew "vim"
brew "yarn"
brew "youtube-dl"
brew "yabai", args: ["HEAD"], restart_service: :changed
brew "skhd", args: ["HEAD"], restart_service: :changed
# brew "koekeishiya/formulae/chunkwm", args: ["HEAD"], restart_service: :changed
# brew "koekeishiya/formulae/skhd", args: ["HEAD"], restart_service: :changed
brew "rs/tap/jaggr"
brew "rs/tap/jplot"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]

# Applications
cask "font-fira-code"
cask "font-hack"
cask "font-input"
cask "hammerspoon"
cask "kitty"
cask "licecap"
cask "ngrok"
cask "oni"
cask "pock"
cask "spotify"
cask "tunnelblick"
cask "ubersicht"


# App Store BS
mas "com.apple.dt.Xcode", id: 497799835
mas "com.evernote.Evernote", id: 406056744
mas "com.ideasoncanvas.mindnode.macos", id: 1289197285
mas "com.if.Amphetamine", id: 937984704
mas "com.microsoft.onenote.mac", id: 784801555
